/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package net.attios

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'net.attios.greeting' plugin.
 */
class CleanCodePluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("net.attios.clean-code")

        then:
        project.tasks.findByName("greeting") != null
    }
}
